import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { readVersions, resolveVersion } from './version.mjs';
import { crateUrl, fetchVerified, parseLockChecksums, requiresMpl, selectMplPackages } from './mpl-sources.mjs';

const CRATES_IO = 'registry+https://github.com/rust-lang/crates.io-index';
const sha = (text) => createHash('sha256').update(text).digest('hex');

test('the checked-in version files agree', () => {
  const version = resolveVersion(readVersions());
  assert.equal(typeof version, 'string', String(version));
});

test('version drift, a mismatched tag and a non-semver version are refused', () => {
  const agreed = { a: '0.3.0', b: '0.3.0', c: '0.3.0' };
  assert.equal(resolveVersion(agreed), '0.3.0');
  assert.equal(resolveVersion(agreed, 'v0.3.0'), '0.3.0');
  assert.match(resolveVersion(agreed, 'v0.3.1').message, /does not match/);
  assert.match(resolveVersion(agreed, '0.3.0').message, /expected v0\.3\.0/);
  assert.match(resolveVersion({ ...agreed, b: '0.2.0' }).message, /b=0\.2\.0/);
  assert.match(resolveVersion({ ...agreed, c: undefined }).message, /no version in c/);
  assert.match(resolveVersion({ a: '1.0' }).message, /not semver/);
});

test('only expressions with no non-MPL alternative oblige MPL source', () => {
  assert.equal(requiresMpl('MPL-2.0'), true);
  assert.equal(requiresMpl('MPL-2.0 AND MIT'), true);
  assert.equal(requiresMpl('MIT OR MPL-2.0'), false);
  assert.equal(requiresMpl('MIT/MPL-2.0'), false);
  assert.equal(requiresMpl('(MIT OR Apache-2.0) AND MPL-2.0'), true, 'unparsed shapes fail closed');
  assert.equal(requiresMpl('MIT OR Apache-2.0'), false);
  assert.equal(requiresMpl(null), false);
});

test('MPL packages are selected with their Cargo.lock checksums, and unpinned ones are refused', () => {
  const lock = [
    '# This file is automatically @generated by Cargo.',
    'version = 4',
    '',
    '[[package]]',
    'name = "selectors"',
    'version = "0.36.1"',
    `source = "${CRATES_IO}"`,
    `checksum = "${'a'.repeat(64)}"`,
    '',
    '[[package]]',
    'name = "serde"',
    'version = "1.0.0"',
    `source = "${CRATES_IO}"`,
    `checksum = "${'b'.repeat(64)}"`,
    '',
    '[[package]]',
    'name = "local-mpl"',
    'version = "0.1.0"',
    ''
  ].join('\n');
  const checksums = parseLockChecksums(lock);
  assert.deepEqual(parseLockChecksums(lock.replace(/\n/g, '\r\n')), checksums, 'a CRLF checkout parses the same');
  assert.equal(checksums.get('selectors@0.36.1').checksum, 'a'.repeat(64));
  const metadata = (extra = []) => ({
    packages: [
      { name: 'serde', version: '1.0.0', license: 'MIT OR Apache-2.0' },
      { name: 'selectors', version: '0.36.1', license: 'MPL-2.0' },
      ...extra
    ]
  });
  assert.deepEqual(selectMplPackages(metadata(), checksums), [
    { name: 'selectors', version: '0.36.1', license: 'MPL-2.0', checksum: 'a'.repeat(64) }
  ]);
  assert.throws(() => selectMplPackages(metadata([{ name: 'local-mpl', version: '0.1.0', license: 'MPL-2.0' }]), checksums),
    /not a checksummed crates\.io package/);
  assert.throws(() => selectMplPackages(metadata([{ name: 'ghost', version: '9.9.9', license: 'MPL-2.0' }]), checksums),
    /not in Cargo\.lock/);
});

test('a downloaded crate that differs from Cargo.lock is refused', async () => {
  const good = Buffer.from('the real crate');
  const pkg = { name: 'selectors', version: '0.36.1', license: 'MPL-2.0', checksum: sha(good) };
  const urls = [];
  const files = await fetchVerified([pkg], async (url) => { urls.push(url); return good; });
  assert.deepEqual(urls, [crateUrl(pkg)]);
  assert.equal(files[0].file, 'selectors-0.36.1.crate');
  await assert.rejects(fetchVerified([pkg], async () => Buffer.from('tampered')), /downloaded sha256 .* != Cargo\.lock/);
});

test('the MPL crates are pinned in Cargo.lock and listed in the notice inventory', () => {
  const lockText = fs.readFileSync(new URL('../../src-tauri/Cargo.lock', import.meta.url), 'utf8');
  const checksums = parseLockChecksums(lockText);
  const inventory = JSON.parse(fs.readFileSync(new URL('../../third-party/inventory.json', import.meta.url), 'utf8'));
  const listed = JSON.stringify(inventory);
  for (const name of ['cssparser', 'cssparser-macros', 'dtoa-short', 'option-ext', 'selectors']) {
    const entry = [...checksums.keys()].find((key) => key.startsWith(`${name}@`));
    assert.ok(entry, `${name} is in Cargo.lock`);
    assert.ok(listed.includes(name), `${name} is in the notice inventory`);
  }
});

test('a release directory must hold exactly the three packages and the shared assets', async () => {
  const { checkDist, expectedAssets } = await import('./assemble.mjs');
  const full = expectedAssets('0.3.0');
  assert.deepEqual(full, [
    'SQLite-Explorer-0.3.0-linux-amd64.deb',
    'SQLite-Explorer-0.3.0-macos-aarch64.dmg',
    'SQLite-Explorer-0.3.0-windows-x64-setup.exe',
    'THIRD_PARTY_NOTICES.txt',
    'mpl-dependency-sources.tar.gz'
  ]);
  assert.equal(checkDist(full, '0.3.0'), null);
  assert.equal(checkDist([...full, 'SHA256SUMS', 'release-manifest.json'], '0.3.0'), null, 'regenerated files are tolerated');
  assert.deepEqual(checkDist(full.filter((n) => !n.endsWith('.deb')), '0.3.0'),
    { missing: ['SQLite-Explorer-0.3.0-linux-amd64.deb'], unexpected: [] });
  assert.deepEqual(checkDist([...full, 'SQLite Explorer_0.3.0_amd64.AppImage'], '0.3.0'),
    { missing: [], unexpected: ['SQLite Explorer_0.3.0_amd64.AppImage'] });
  assert.ok(checkDist(full, '0.3.1'), 'assets of another version are not this release');
});

test('SHA256SUMS is sha256sum-compatible and sorted', async () => {
  const { checksumsText } = await import('./assemble.mjs');
  assert.equal(checksumsText([{ name: 'b', sha256: '2'.repeat(64) }, { name: 'a', sha256: '1'.repeat(64) }]),
    `${'1'.repeat(64)}  a\n${'2'.repeat(64)}  b\n`);
});

test('assemble writes a manifest and checksums that verify, and refuses a polluted directory', async () => {
  const { execFileSync } = await import('node:child_process');
  const os = await import('node:os');
  const path = await import('node:path');
  const { expectedAssets } = await import('./assemble.mjs');
  const version = resolveVersion(readVersions());
  const dist = fs.mkdtempSync(path.join(os.tmpdir(), 'assemble-test-'));
  try {
    for (const name of expectedAssets(version)) fs.writeFileSync(path.join(dist, name), `bytes of ${name}`);
    const run = (tag) => execFileSync(process.execPath, [fileURLToPath(new URL('./assemble.mjs', import.meta.url)), 'assemble',
      '--dist', dist, '--tag', tag, '--commit', 'c'.repeat(40), '--run-url', 'https://example.invalid/run',
      '--notes', path.join(dist, '..', `${path.basename(dist)}-notes.md`)], { encoding: 'utf8', stdio: 'pipe' });
    run(`v${version}`);
    const manifest = JSON.parse(fs.readFileSync(path.join(dist, 'release-manifest.json'), 'utf8'));
    assert.equal(manifest.version, version);
    assert.equal(manifest.assets.length, expectedAssets(version).length);
    for (const line of fs.readFileSync(path.join(dist, 'SHA256SUMS'), 'utf8').trim().split('\n')) {
      const [hash, name] = line.split('  ');
      assert.equal(createHash('sha256').update(fs.readFileSync(path.join(dist, name))).digest('hex'), hash, name);
    }
    assert.throws(() => run('v0.0.0-not-this'), /does not match/);
    fs.writeFileSync(path.join(dist, 'stray.zip'), 'x');
    assert.throws(() => run(`v${version}`), /unexpected \[stray\.zip\]/);
  } finally {
    fs.rmSync(dist, { recursive: true, force: true });
    fs.rmSync(`${dist}-notes.md`, { force: true });
  }
});

test('the bundled notices name no specific release and point at every release for MPL sources', () => {
  // The same file ships inside every package of every version, so its header
  // must not pin one release: a stale tag URL sends MPL source requests to a
  // release that does not exist.
  const notices = fs.readFileSync(new URL('../../THIRD_PARTY_NOTICES.txt', import.meta.url), 'utf8');
  const header = notices.slice(0, notices.indexOf('\n====='));
  assert.doesNotMatch(header, /\/releases\/tag\//, 'no pinned release URL');
  assert.doesNotMatch(header, /\bbeta\b/i, 'no beta wording');
  assert.doesNotMatch(header.split('\n')[0], /\d+\.\d+\.\d+/, 'no version in the title');
  assert.match(header, /mpl-dependency-sources\.tar\.gz/);
  assert.match(header, /https:\/\/github\.com\/zknpr\/SQLite-Explorer-App\/releases(?!\/tag)/);
});

test('a prerelease version drafts a prerelease, and the manifest states the DMG is unsigned', async () => {
  const { buildManifest } = await import('./assemble.mjs');
  const base = { tag: 'v', commit: 'c'.repeat(40), runUrl: 'u', viewerRef: 'r', assets: [] };
  assert.equal(buildManifest({ ...base, version: '0.3.0-beta.1' }).prerelease, true);
  assert.equal(buildManifest({ ...base, version: '0.3.0' }).prerelease, false);
  assert.match(buildManifest({ ...base, version: '0.3.0' }).signing.macos, /disk image is unsigned/);
});

test('the release notes give a checksum command that exists on each platform', async () => {
  const { releaseNotes } = await import('./assemble.mjs');
  const notes = releaseNotes({ version: '0.3.0', commit: 'c'.repeat(40), runUrl: 'u', viewerRef: 'r' });
  assert.match(notes, /shasum -a 256 --check --ignore-missing SHA256SUMS/, 'macOS');
  assert.match(notes, /Get-FileHash/, 'Windows');
  assert.match(notes, /sha256sum --check --ignore-missing SHA256SUMS/, 'Linux');
});
