#!/usr/bin/env bash
# Generate a >300 MB SQLite database to prove the NATIVE engine opens files the
# WASM engine cannot (sql.js inhales the whole file into wasm memory and falls
# over on large DBs; the tjs sidecar opens the file on disk). CTE-driven; the
# produced .db is throwaway and is NEVER committed — regenerate on demand.
#
#   make-big-db.sh <path> [target_mb]   (default 350)
set -euo pipefail
DB="${1:?usage: make-big-db.sh <path> [target_mb]}"
TARGET_MB="${2:-350}"
rm -f "$DB" "$DB-wal" "$DB-shm"

# ~1 KB per row (blob payload keeps 8 KiB pages full); rows = target_mb * 1024.
ROWS=$(( TARGET_MB * 1024 ))

sqlite3 "$DB" <<EOF
PRAGMA page_size = 8192;
PRAGMA journal_mode = OFF;
PRAGMA synchronous = OFF;
CREATE TABLE bulk (id INTEGER PRIMARY KEY, payload BLOB NOT NULL, tag TEXT);
WITH RECURSIVE seq(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM seq WHERE x < $ROWS)
INSERT INTO bulk (payload, tag) SELECT randomblob(1024), 'row-' || x FROM seq;
CREATE INDEX idx_bulk_tag ON bulk(tag);
-- A tiny second table so schema navigation has something small to render too.
CREATE TABLE marker (note TEXT);
INSERT INTO marker (note) VALUES ('generated by make-big-db.sh — native-open smoke fixture');
EOF

SIZE_BYTES=$(stat -f%z "$DB" 2>/dev/null || stat -c%s "$DB")
SIZE_H=$(du -h "$DB" | cut -f1)
echo "created $DB ($SIZE_H, ${SIZE_BYTES} bytes, $ROWS rows)"
if [ "$SIZE_BYTES" -lt 314572800 ]; then
  echo "WARNING: under 300 MiB — raise target_mb to exceed the WASM open ceiling" >&2
fi
