
// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
// In addition, When you use emcc's modularization, it still expects to export a global object called `Module`,
// which is able to be used/called before the WASM is loaded.
// The modularization below exports a promise that loads and resolves to the actual sql.js module.
// That way, this module can't be used before the WASM is finished loading.

// We are going to define a function that a user will call to start loading initializing our Sql.js library
// However, that function might be called multiple times, and on subsequent calls, we don't actually want it to instantiate a new instance of the Module
// Instead, we want to return the previously loaded module

// TODO: Make this not declare a global if used in the browser
var initSqlJsPromise = undefined;

var initSqlJs = function (moduleConfig) {

    if (initSqlJsPromise){
      return initSqlJsPromise;
    }
    // If we're here, we've never called this function before
    initSqlJsPromise = new Promise(function (resolveModule, reject) {

        // We are modularizing this manually because the current modularize setting in Emscripten has some issues:
        // https://github.com/kripken/emscripten/issues/5820

        // The way to affect the loading of emcc compiled modules is to create a variable called `Module` and add
        // properties to it, like `preRun`, `postRun`, etc
        // We are using that to get notified when the WASM has finished loading.
        // Only then will we return our promise

        // If they passed in a moduleConfig object, use that
        // Otherwise, initialize Module to the empty object
        var Module = typeof moduleConfig !== 'undefined' ? moduleConfig : {};

        // EMCC only allows for a single onAbort function (not an array of functions)
        // So if the user defined their own onAbort function, we remember it and call it
        var originalOnAbortFunction = Module['onAbort'];
        Module['onAbort'] = function (errorThatCausedAbort) {
            reject(new Error(errorThatCausedAbort));
            if (originalOnAbortFunction){
              originalOnAbortFunction(errorThatCausedAbort);
            }
        };

        Module['postRun'] = Module['postRun'] || [];
        Module['postRun'].push(function () {
            // When Emscripted calls postRun, this promise resolves with the built Module
            resolveModule(Module);
        });

        // There is a section of code in the emcc-generated code below that looks like this:
        // (Note that this is lowercase `module`)
        // if (typeof module !== 'undefined') {
        //     module['exports'] = Module;
        // }
        // When that runs, it's going to overwrite our own modularization export efforts in shell-post.js!
        // The only way to tell emcc not to emit it is to pass the MODULARIZE=1 or MODULARIZE_INSTANCE=1 flags,
        // but that carries with it additional unnecessary baggage/bugs we don't want either.
        // So, we have three options:
        // 1) We undefine `module`
        // 2) We remember what `module['exports']` was at the beginning of this function and we restore it later
        // 3) We write a script to remove those lines of code as part of the Make process.
        //
        // Since those are the only lines of code that care about module, we will undefine it. It's the most straightforward
        // of the options, and has the side effect of reducing emcc's efforts to modify the module if its output were to change in the future.
        // That's a nice side effect since we're handling the modularization efforts ourselves
        module = undefined;

        // The emcc-generated code and shell-post.js code goes below,
        // meaning that all of it runs inside of this promise. If anything throws an exception, our promise will abort
var l;l||=typeof Module != 'undefined' ? Module : {};var ca=!!globalThis.window,da=!!globalThis.WorkerGlobalScope,ea=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;
l.onRuntimeInitialized=function(){function a(e,h){switch(typeof h){case "boolean":Bc(e,h?1:0);break;case "number":Cc(e,h);break;case "string":Dc(e,h,-1,-1);break;case "object":if(null===h)Gb(e);else if(null!=h.length){var k=ha(h.length);n.set(h,k);Ec(e,k,h.length,-1);ia(k)}else Ia(e,"Wrong API use : tried to return a value of an unknown type ("+h+").",-1);break;default:Gb(e)}}function b(e,h){for(var k=[],m=0;m<e;m+=1){var q=w(h+4*m,"i32"),r=Fc(q);if(1===r||2===r)q=Gc(q);else if(3===r)q=Hc(q);else if(4===
r){r=q;q=Ic(r);r=Jc(r);for(var y=new Uint8Array(q),u=0;u<q;u+=1)y[u]=n[r+u];q=y}else q=null;k.push(q)}return k}function c(e,h){this.Ya=e;this.db=h;this.Wa=1;this.Bb=[];this.ob=null;this.ub=!1}function d(e){if(null===e.ob){e.ob=[];for(var h=Kc(e.Ya),k=0;k<h;k+=1)e.ob.push(Lc(e.Ya,k))}return e.ob}function f(e,h){this.db=h;this.vb=ja(e);if(null===this.vb)throw Error("Unable to allocate memory for the SQL string");this.Ab=this.vb;this.mb=this.Hb=null}function g(e){this.filename="dbfile_"+(4294967295*
Math.random()>>>0);if(null!=e){var h=this.filename,k="/",m=h;k&&(k="string"==typeof k?k:ka(k),m=h?la(k+"/"+h):k);h=ma(!0,!0);m=na(m,h);if(e){if("string"==typeof e){k=Array(e.length);for(var q=0,r=e.length;q<r;++q)k[q]=e.charCodeAt(q);e=k}qa(m,h|146);k=ra(m,577);sa(k,e,0,e.length,0);ta(k);qa(m,h)}}this.handleError(Jb(this.filename,J));this.db=w(J,"i32");La(this.db);this.kb={};this.Za={}}function p(e,h,k,m){var q=Z[e];e=aa[e];if(!q)return-1;m=Number(m);if(0>m||!Number.isSafeInteger(m))return-1;try{if(e){a:{var r=
e.chunkSize,y=e.cb-m;var u=0;var A=m;var F,N;for(y>k&&(y=k);u<y;){var K=Math.floor(A/r);var S=A-K*r;var P=r-S;P>y-u&&(P=y-u);if(F=e.lb.get(K))C.set(F.subarray(S,S+P),h+u);else{var M=e.nb-A;M>P&&(M=P);if(0<M){var fa=(N=q.read(A,M))?N.length:0;fa>M&&(N=N.subarray(0,M),fa=M);0<fa&&C.set(N,h+u);if(fa<M){var oa=u+fa;break a}}else M=0;P>M&&C.fill(0,h+u+M,h+u+P)}u+=P;A+=P}oa=u}return oa}u=q.read(m,k);if(null==u)return 0;A=u.length;A>k&&(u=u.subarray(0,k),A=k);C.set(u,h);return A}catch(Ma){return-1}}function v(e){var h=
Z[e];e=aa[e];if(!h)return-1;if(e)return e.cb;try{var k=h.size()}catch(m){return-1}return"number"!==typeof k||0>k||!Number.isSafeInteger(k)?-1:k}function z(e,h){var k=e.chunkSize,m=[];h<e.cb&&(e.lb.forEach(function(q,r){var y=r*k;y>=h?m.push(r):y+k>h&&q.fill(0,h-y)}),m.forEach(function(q){e.lb.delete(q)}),h<e.nb&&(e.nb=h));e.cb=h}function x(e,h,k,m){var q=Z[e];e=aa[e];if(!q||!e)return-1;m=Number(m);if(0>m||!Number.isSafeInteger(m)||0>k)return-1;try{for(var r=e.chunkSize,y=m,u=0,A,F,N,K,S;u<k;){A=Math.floor(y/
r);F=A*r;N=y-F;K=r-N;K>k-u&&(K=k-u);S=e.lb.get(A);if(!S){S=new Uint8Array(r);if(K<r){var P=void 0,M=void 0,fa=q,oa=S,Ma=F,ba=e.nb-Ma;if(!(0>=ba)){ba>oa.length&&(ba=oa.length);P=(M=fa.read(Ma,ba))?M.length:0;P>ba&&(M=M.subarray(0,ba),P=ba);if(P<ba)throw Error("paged base file returned a short read at offset "+Ma);oa.set(M,0)}}e.lb.set(A,S)}S.set(C.subarray(h+u,h+u+K),N);y+=K;u+=K}m+k>e.cb&&(e.cb=m+k);return 0}catch(Ed){return-1}}function B(e,h){e=aa[e];if(!e)return-1;h=Number(h);if(0>h||!Number.isSafeInteger(h))return-1;
try{return z(e,h),0}catch(k){return-1}}function L(){throw Error("paged databases are read-only snapshots; export() is only available on openPagedWritable instances");}function hb(){var e,h,k;if(null===this.db)throw Error("Database closed");if(0===Kb(this.db))throw Error("cannot export a paged database while a transaction is open; COMMIT or ROLLBACK first");var m=aa[this.tb];var q=Z[this.tb];var r=m.chunkSize;var y=new Uint8Array(m.cb);for(e=0;e<m.cb;){var u=r;u>m.cb-e&&(u=m.cb-e);if(h=m.lb.get(e/
r))y.set(h.subarray(0,u),e);else if(h=m.nb-e,h>u&&(h=u),0<h){(k=q.read(e,h))&&k.length>h&&(k=k.subarray(0,h));if(!k||k.length<h)throw Error("paged base file returned a short read during export (offset "+e+")");y.set(k,e)}e+=u}return y}function Lb(){var e=[];if(null===this.db)throw Error("Database closed");if(0===Kb(this.db))throw Error("cannot export a paged database while a transaction is open; COMMIT or ROLLBACK first");var h=aa[this.tb];h.lb.forEach(function(k,m){e.push({index:m,data:k.slice()})});
e.sort(function(k,m){return k.index-m.index});return{chunkSize:h.chunkSize,logicalSize:h.cb,baseLimit:h.nb,chunks:e}}function Na(){null!==this.db&&(Object.values(this.kb).forEach(function(e){e.ib()}),Object.values(this.Za).forEach(D),this.Za={},this.ab&&(va(this.db,0,0,0),D(this.ab),this.ab=void 0),this.hb&&(D(this.hb),this.hb=void 0),this.handleError(wa(this.db)),delete Z[this.tb],delete aa[this.tb],this.db=null)}var J=ua(4),t=l.cwrap,Jb=t("sqlite3_open","number",["string","number"]),wa=t("sqlite3_close_v2",
"number",["number"]),Nc=t("sqlite3_exec","number",["number","string","number","number","number"]),Oc=t("sqlite3_changes","number",["number"]),Pc=t("sqlite3_prepare_v2","number",["number","string","number","number","number"]),Qc=t("sqlite3_sql","string",["number"]),Rc=t("sqlite3_normalized_sql","string",["number"]),Mb=t("sqlite3_prepare_v2","number",["number","number","number","number","number"]),Sc=t("sqlite3_bind_text","number",["number","number","number","number","number"]),Nb=t("sqlite3_bind_blob",
"number",["number","number","number","number","number"]),Tc=t("sqlite3_bind_double","number",["number","number","number"]),Uc=t("sqlite3_bind_int","number",["number","number","number"]),Vc=t("sqlite3_bind_parameter_index","number",["number","string"]),Wc=t("sqlite3_step","number",["number"]),ib=t("sqlite3_errmsg","string",["number"]),Kc=t("sqlite3_column_count","number",["number"]),Xc=t("sqlite3_data_count","number",["number"]),Yc=t("sqlite3_column_double","number",["number","number"]),Ob=t("sqlite3_column_text",
"string",["number","number"]),Zc=t("sqlite3_column_blob","number",["number","number"]),$c=t("sqlite3_column_bytes","number",["number","number"]),ad=t("sqlite3_column_type","number",["number","number"]),Lc=t("sqlite3_column_name","string",["number","number"]),bd=t("sqlite3_reset","number",["number"]),cd=t("sqlite3_clear_bindings","number",["number"]),dd=t("sqlite3_finalize","number",["number"]),Pb=t("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),
Fc=t("sqlite3_value_type","number",["number"]),Ic=t("sqlite3_value_bytes","number",["number"]),Hc=t("sqlite3_value_text","string",["number"]),Jc=t("sqlite3_value_blob","number",["number"]),Gc=t("sqlite3_value_double","number",["number"]),Cc=t("sqlite3_result_double","",["number","number"]),Gb=t("sqlite3_result_null","",["number"]),Dc=t("sqlite3_result_text","",["number","string","number","number"]),Ec=t("sqlite3_result_blob","",["number","number","number","number"]),Bc=t("sqlite3_result_int","",["number",
"number"]),Ia=t("sqlite3_result_error","",["number","string","number"]),Qb=t("sqlite3_aggregate_context","number",["number","number"]),La=t("RegisterExtensionFunctions","number",["number"]),Rb=t("sqlite3_update_hook","number",["number","number","number"]),va=t("sqlite3_progress_handler","",["number","number","number","number"]),ed=t("sqlite3_interrupt","",["number"]),Kb=t("sqlite3_get_autocommit","number",["number"]),Sb=t("sqljs_vfs_register","number",["number","number"]),fd=t("sqljs_open_paged",
"number",["number","number"]),gd=t("sqljs_vfs_register_rw","number",["number","number"]),hd=t("sqljs_open_paged_rw","number",["number","number"]);c.prototype.bind=function(e){if(!this.Ya)throw"Statement closed";this.reset();return Array.isArray(e)?this.Wb(e):null!=e&&"object"===typeof e?this.Xb(e):!0};c.prototype.step=function(){if(!this.Ya)throw"Statement closed";this.ub||(this.ob=null);this.Wa=1;var e=Wc(this.Ya);switch(e){case 100:return this.ub=!0;case 101:return this.ub=!1;default:throw this.ub=
!1,this.db.handleError(e);}};c.prototype.Qb=function(e){null==e&&(e=this.Wa,this.Wa+=1);return Yc(this.Ya,e)};c.prototype.cc=function(e){null==e&&(e=this.Wa,this.Wa+=1);e=Ob(this.Ya,e);if("function"!==typeof BigInt)throw Error("BigInt is not supported");return BigInt(e)};c.prototype.ic=function(e){null==e&&(e=this.Wa,this.Wa+=1);return Ob(this.Ya,e)};c.prototype.getBlob=function(e){null==e&&(e=this.Wa,this.Wa+=1);var h=$c(this.Ya,e);e=Zc(this.Ya,e);return C.slice(e,e+h)};c.prototype.get=function(e,
h){h=h&&h.useBigInt;null!=e&&this.bind(e)&&this.step();e=Xc(this.Ya);for(var k=Array(e),m=0;m<e;m+=1)switch(ad(this.Ya,m)){case 1:var q=h?this.cc(m):this.Qb(m);k[m]=q;break;case 2:k[m]=this.Qb(m);break;case 3:k[m]=this.ic(m);break;case 4:k[m]=this.getBlob(m);break;default:k[m]=null}return k};c.prototype.Pb=function(){return d(this).slice()};c.prototype.Ob=function(e,h){e=this.get(e,h);h=d(this);for(var k={},m=0;m<h.length;m+=1)k[h[m]]=e[m];return k};c.prototype.hc=function(){return Qc(this.Ya)};c.prototype.dc=
function(){return Rc(this.Ya)};c.prototype.run=function(e){null!=e&&this.bind(e);this.step();return this.reset()};c.prototype.Lb=function(e,h){null==h&&(h=this.Wa,this.Wa+=1);e=ja(e);this.Bb.push(e);this.db.handleError(Sc(this.Ya,h,e,-1,0))};c.prototype.Vb=function(e,h){null==h&&(h=this.Wa,this.Wa+=1);var k=ha(e.length);n.set(e,k);this.Bb.push(k);this.db.handleError(Nb(this.Ya,h,k,e.length,0))};c.prototype.Kb=function(e,h){null==h&&(h=this.Wa,this.Wa+=1);this.db.handleError((e===(e|0)?Uc:Tc)(this.Ya,
h,e))};c.prototype.Yb=function(e){null==e&&(e=this.Wa,this.Wa+=1);Nb(this.Ya,e,0,0,0)};c.prototype.Mb=function(e,h){null==h&&(h=this.Wa,this.Wa+=1);switch(typeof e){case "string":this.Lb(e,h);return;case "number":this.Kb(e,h);return;case "bigint":this.Lb(e.toString(),h);return;case "boolean":this.Kb(e+0,h);return;case "object":if(null===e){this.Yb(h);return}if(null!=e.length){this.Vb(e,h);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+e+").";};c.prototype.Xb=function(e){var h=
this;Object.keys(e).forEach(function(k){var m=Vc(h.Ya,k);0!==m&&h.Mb(e[k],m)});return!0};c.prototype.Wb=function(e){for(var h=0;h<e.length;h+=1)this.Mb(e[h],h+1);return!0};c.prototype.reset=function(){this.ob=null;this.ub=!1;this.freemem();return 0===cd(this.Ya)&&0===bd(this.Ya)};c.prototype.freemem=function(){for(var e;void 0!==(e=this.Bb.pop());)ia(e)};c.prototype.ib=function(){this.freemem();var e=0===dd(this.Ya);delete this.db.kb[this.Ya];this.Ya=0;return e};f.prototype.next=function(){if(null===
this.vb)return{done:!0};null!==this.mb&&(this.mb.ib(),this.mb=null);if(!this.db.db)throw this.Eb(),Error("Database closed");var e=xa(),h=ua(4);ya(J);ya(h);try{this.db.handleError(Mb(this.db.db,this.Ab,-1,J,h));this.Ab=w(h,"i32");var k=w(J,"i32");if(0===k)return this.Eb(),{done:!0};this.mb=new c(k,this.db);this.db.kb[k]=this.mb;return{value:this.mb,done:!1}}catch(m){throw this.Hb=E(this.Ab),this.Eb(),m;}finally{za(e)}};f.prototype.Eb=function(){ia(this.vb);this.vb=null};f.prototype.ec=function(){return null!==
this.Hb?this.Hb:E(this.Ab)};"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator&&(f.prototype[Symbol.iterator]=function(){return this});g.prototype.run=function(e,h){if(!this.db)throw"Database closed";if(h){e=this.Ib(e,h);try{e.step()}finally{e.ib()}}else this.handleError(Nc(this.db,e,0,0,J));return this};g.prototype.exec=function(e,h,k){if(!this.db)throw"Database closed";var m=xa(),q=null,r=null,y=null;try{y=r=ja(e);var u=ua(4);for(e=[];0!==w(y,"i8");){ya(J);ya(u);this.handleError(Mb(this.db,
y,-1,J,u));var A=w(J,"i32");y=w(u,"i32");if(0!==A){var F=null;q=new c(A,this);for(null!=h&&q.bind(h);q.step();)null===F&&(F={columns:q.Pb(),values:[]},e.push(F)),F.values.push(q.get(null,k));q.ib()}}return e}catch(N){throw q&&q.ib(),N;}finally{r&&ia(r),za(m)}};g.prototype.bc=function(e,h,k,m,q){"function"===typeof h&&(m=k,k=h,h=void 0);e=this.Ib(e,h);try{for(;e.step();)k(e.Ob(null,q))}finally{e.ib()}if("function"===typeof m)return m()};g.prototype.Ib=function(e,h){ya(J);this.handleError(Pc(this.db,
e,-1,J,0));e=w(J,"i32");if(0===e)throw"Nothing to prepare";var k=new c(e,this);null!=h&&k.bind(h);return this.kb[e]=k};g.prototype.kc=function(e){return new f(e,this)};g.prototype.Db=function(){Object.values(this.kb).forEach(function(h){h.ib()});Object.values(this.Za).forEach(D);this.Za={};this.ab&&(va(this.db,0,0,0),D(this.ab),this.ab=void 0);this.handleError(wa(this.db));var e=Aa(this.filename);this.handleError(Jb(this.filename,J));this.db=w(J,"i32");La(this.db);return e};g.prototype.close=function(){null!==
this.db&&(Object.values(this.kb).forEach(function(e){e.ib()}),Object.values(this.Za).forEach(D),this.Za={},this.ab&&(va(this.db,0,0,0),D(this.ab),this.ab=void 0),this.hb&&(D(this.hb),this.hb=void 0),this.handleError(wa(this.db)),Ba("/"+this.filename),this.db=null)};g.prototype.handleError=function(e){if(0===e)return null;e=ib(this.db);throw Error(e);};g.prototype.fc=function(){return Oc(this.db)};g.prototype.nc=function(e,h){if(!this.db)throw"Database closed";this.ab&&(va(this.db,0,0,0),D(this.ab),
this.ab=void 0);if(null===h||"undefined"===typeof h)return this;this.ab=G(function(){try{return h()?1:0}catch(k){return 1}},"ii");va(this.db,e,this.ab,0);return this};g.prototype.jc=function(){if(!this.db)throw"Database closed";ed(this.db);return this};g.prototype.$b=function(e,h){Object.prototype.hasOwnProperty.call(this.Za,e)&&(D(this.Za[e]),delete this.Za[e]);var k=G(function(m,q,r){q=b(q,r);try{var y=h.apply(null,q)}catch(u){Ia(m,u,-1);return}a(m,y)},"viii");this.Za[e]=k;this.handleError(Pb(this.db,
e,h.length,1,0,k,0,0,0));return this};g.prototype.Zb=function(e,h){var k=h.init||function(){return null},m=h.finalize||function(A){return A},q=h.step;if(!q)throw"An aggregate function must have a step function in "+e;var r={};Object.hasOwnProperty.call(this.Za,e)&&(D(this.Za[e]),delete this.Za[e]);h=e+"__finalize";Object.hasOwnProperty.call(this.Za,h)&&(D(this.Za[h]),delete this.Za[h]);var y=G(function(A,F,N){var K=Qb(A,1);Object.hasOwnProperty.call(r,K)||(r[K]=k());F=b(F,N);F=[r[K]].concat(F);try{r[K]=
q.apply(null,F)}catch(S){delete r[K],Ia(A,S,-1)}},"viii"),u=G(function(A){var F=Qb(A,1);try{var N=m(r[F])}catch(K){delete r[F];Ia(A,K,-1);return}a(A,N);delete r[F]},"vi");this.Za[e]=y;this.Za[h]=u;this.handleError(Pb(this.db,e,q.length-1,1,0,0,y,u,0));return this};g.prototype.qc=function(e){this.hb&&(Rb(this.db,0,0),D(this.hb),this.hb=void 0);if(!e)return this;this.hb=G(function(h,k,m,q,r){switch(k){case 18:h="insert";break;case 23:h="update";break;case 9:h="delete";break;default:throw"unknown operationCode in updateHook callback: "+
k;}m=E(m);q=E(q);if(r>Number.MAX_SAFE_INTEGER)throw"rowId too big to fit inside a Number";e(h,m,q,Number(r))},"viiiij");Rb(this.db,this.hb,0);return this};var Z={},aa={},Oa=1,pa=null,Pa=null,jb=null,Ub=null;g.openPaged=function(e){if(!e||"function"!==typeof e.read||"function"!==typeof e.size)throw Error("openPaged requires a hostIo object with read(offset, length) and size() functions");null===pa&&(pa=G(p,"iiiij"),Pa=G(v,"di"));var h=Sb(pa,Pa);if(0!==h)throw Error("could not register the sqljs_host VFS (error code "+
h+")");var k=Oa;Oa+=1;Z[k]=e;try{h=fd(k,J);var m=w(J,"i32");if(0!==h){var q=0!==m?ib(m):"SQLite error "+h;0!==m&&wa(m);throw Error(q);}}catch(r){throw delete Z[k],r;}e=Object.create(g.prototype);e.db=m;e.filename=null;e.tb=k;e.kb={};e.Za={};La(e.db);e.Db=L;e["export"]=L;e.close=Na;e.close=Na;return e};g.openPagedWritable=function(e){if(!e||"function"!==typeof e.read||"function"!==typeof e.size)throw Error("openPagedWritable requires a hostIo object with read(offset, length) and size() functions");
var h=e.size();if("number"!==typeof h||0>h||!Number.isSafeInteger(h))throw Error("hostIo.size() must return a non-negative byte count");null===pa&&(pa=G(p,"iiiij"),Pa=G(v,"di"));null===jb&&(jb=G(x,"iiiij"),Ub=G(B,"iij"));var k=Sb(pa,Pa);0===k&&(k=gd(jb,Ub));if(0!==k)throw Error("could not register the sqljs_host VFS (error code "+k+")");var m=Oa;Oa+=1;Z[m]=e;a:{try{var q=e.read(16,2)}catch(u){e=4096;break a}!q||2>q.length?e=4096:(e=256*q[0]+q[1],e=1===e?65536:512<=e&&32768>=e&&0===(e&e-1)?e:4096)}aa[m]=
{chunkSize:e,lb:new Map,cb:h,nb:h};try{k=hd(m,J);var r=w(J,"i32");if(0!==k){var y=0!==r?ib(r):"SQLite error "+k;0!==r&&wa(r);throw Error(y);}}catch(u){throw delete Z[m],delete aa[m],u;}k=Object.create(g.prototype);k.db=r;k.filename=null;k.tb=m;k.kb={};k.Za={};La(k.db);k.Db=hb;k["export"]=hb;k.xc=Lb;k.exportPagedWritableOverlay=Lb;k.close=Na;k.close=Na;return k};c.prototype.bind=c.prototype.bind;c.prototype.step=c.prototype.step;c.prototype.get=c.prototype.get;c.prototype.getColumnNames=c.prototype.Pb;
c.prototype.getAsObject=c.prototype.Ob;c.prototype.getSQL=c.prototype.hc;c.prototype.getNormalizedSQL=c.prototype.dc;c.prototype.run=c.prototype.run;c.prototype.reset=c.prototype.reset;c.prototype.freemem=c.prototype.freemem;c.prototype.free=c.prototype.ib;f.prototype.next=f.prototype.next;f.prototype.getRemainingSQL=f.prototype.ec;g.prototype.run=g.prototype.run;g.prototype.exec=g.prototype.exec;g.prototype.each=g.prototype.bc;g.prototype.prepare=g.prototype.Ib;g.prototype.iterateStatements=g.prototype.kc;
g.prototype["export"]=g.prototype.Db;g.prototype.close=g.prototype.close;g.prototype.handleError=g.prototype.handleError;g.prototype.getRowsModified=g.prototype.fc;g.prototype.progress_handler=g.prototype.nc;g.prototype.interrupt=g.prototype.jc;g.prototype.create_function=g.prototype.$b;g.prototype.create_aggregate=g.prototype.Zb;g.prototype.updateHook=g.prototype.qc;l.Database=g};var Ca="./this.program",Da=(a,b)=>{throw b;},Ea=globalThis.document?.currentScript?.src;
"undefined"!=typeof __filename?Ea=__filename:da&&(Ea=self.location.href);var Fa="",Ga,Ha;
if(ea){var fs=require("node:fs");Fa=__dirname+"/";Ha=a=>{a=Ja(a)?new URL(a):a;return fs.readFileSync(a)};Ga=async a=>{a=Ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(Ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=l);Da=(a,b)=>{process.exitCode=a;throw b;}}else if(ca||da){try{Fa=(new URL(".",Ea)).href}catch{}da&&(Ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
Ga=async a=>{if(Ja(a))return new Promise((c,d)=>{var f=new XMLHttpRequest;f.open("GET",a,!0);f.responseType="arraybuffer";f.onload=()=>{200==f.status||0==f.status&&f.response?c(f.response):d(f.status)};f.onerror=d;f.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var Ka=console.log.bind(console),Qa=console.error.bind(console),Ra,Sa=!1,Ta,Ja=a=>a.startsWith("file://"),n,C,Ua,H,I,Va,Wa,O;
function Xa(){var a=Ya.buffer;n=new Int8Array(a);Ua=new Int16Array(a);C=new Uint8Array(a);new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);Va=new Float32Array(a);Wa=new Float64Array(a);O=new BigInt64Array(a);new BigUint64Array(a)}function Za(a){l.onAbort?.(a);a="Aborted("+a+")";Qa(a);Sa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var $a;
async function ab(a){if(!Ra)try{var b=await Ga(a);return new Uint8Array(b)}catch{}if(a==$a&&Ra)a=new Uint8Array(Ra);else if(Ha)a=Ha(a);else throw"both async and sync fetching of the wasm failed";return a}async function bb(a,b){try{var c=await ab(a);return await WebAssembly.instantiate(c,b)}catch(d){Qa(`failed to asynchronously prepare wasm: ${d}`),Za(d)}}
async function cb(a){var b=$a;if(!Ra&&!Ja(b)&&!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){Qa(`wasm streaming compile failed: ${d}`),Qa("falling back to ArrayBuffer instantiation")}return bb(b,a)}class db{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var eb=a=>{for(;0<a.length;)a.shift()(l)},fb=[],gb=[],kb=()=>{var a=l.preRun.shift();gb.push(a)},lb=0,mb=null;
function w(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return n[a];case "i8":return n[a];case "i16":return Ua[a>>1];case "i32":return H[a>>2];case "i64":return O[a>>3];case "float":return Va[a>>2];case "double":return Wa[a>>3];case "*":return I[a>>2];default:Za(`invalid type for getValue: ${b}`)}}var nb=!0;
function ya(a){var b="i32";b.endsWith("*")&&(b="*");switch(b){case "i1":n[a]=0;break;case "i8":n[a]=0;break;case "i16":Ua[a>>1]=0;break;case "i32":H[a>>2]=0;break;case "i64":O[a>>3]=BigInt(0);break;case "float":Va[a>>2]=0;break;case "double":Wa[a>>3]=0;break;case "*":I[a>>2]=0;break;default:Za(`invalid type for setValue: ${b}`)}}
var ob=new TextDecoder,pb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},E=(a,b,c)=>a?ob.decode(C.subarray(a,pb(C,a,b,c))):"",qb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},la=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=qb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},rb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},sb=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],tb=()=>{if(ea){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},ub=a=>{(ub=tb())(a)},vb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=qb(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":
"")+b||"."},wb=a=>{var b=pb(a,0);return ob.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},xb=[],yb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Q=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var p=a.codePointAt(g);if(127>=p){if(c>=d)break;b[c++]=p}else if(2047>=p){if(c+1>=d)break;b[c++]=192|p>>6;b[c++]=128|p&63}else if(65535>=p){if(c+2>=d)break;b[c++]=224|p>>12;b[c++]=128|
p>>6&63;b[c++]=128|p&63}else{if(c+3>=d)break;b[c++]=240|p>>18;b[c++]=128|p>>12&63;b[c++]=128|p>>6&63;b[c++]=128|p&63;g++}}b[c]=0;return c-f},zb=[];function Ab(a,b){zb[a]={input:[],output:[],sb:b};Bb(a,Cb)}
var Cb={open(a){var b=zb[a.node.rdev];if(!b)throw new R(43);a.tty=b;a.seekable=!1},close(a){a.tty.sb.fsync(a.tty)},fsync(a){a.tty.sb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.sb.Rb)throw new R(60);for(var f=0,g=0;g<d;g++){try{var p=a.tty.sb.Rb(a.tty)}catch(v){throw new R(29);}if(void 0===p&&0===f)throw new R(6);if(null===p||void 0===p)break;f++;b[c+g]=p}f&&(a.node.atime=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.sb.Jb)throw new R(60);try{for(var f=0;f<d;f++)a.tty.sb.Jb(a.tty,b[c+f])}catch(g){throw new R(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return f}},Db={Rb(){a:{if(!xb.length){var a=null;if(ea){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}b=Array(yb(a)+1);a=Q(a,b,0,b.length);b.length=a;xb=b}a=xb.shift()}return a},Jb(a,b){null===b||10===b?(Ka(wb(a.output)),a.output=
[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(Ka(wb(a.output)),a.output=[])},zc(){return{tc:25856,vc:5,sc:191,uc:35387,rc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ac(){return 0},Bc(){return[24,80]}},Eb={Jb(a,b){null===b||10===b?(Qa(wb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(Qa(wb(a.output)),a.output=[])}},T={gb:null,jb(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&
61440))throw new R(63);T.gb||(T.gb={dir:{node:{bb:T.Ta.bb,eb:T.Ta.eb,lookup:T.Ta.lookup,xb:T.Ta.xb,rename:T.Ta.rename,unlink:T.Ta.unlink,rmdir:T.Ta.rmdir,readdir:T.Ta.readdir,symlink:T.Ta.symlink},stream:{fb:T.Ua.fb}},file:{node:{bb:T.Ta.bb,eb:T.Ta.eb},stream:{fb:T.Ua.fb,read:T.Ua.read,write:T.Ua.write,yb:T.Ua.yb,zb:T.Ua.zb}},link:{node:{bb:T.Ta.bb,eb:T.Ta.eb,readlink:T.Ta.readlink},stream:{}},Nb:{node:{bb:T.Ta.bb,eb:T.Ta.eb},stream:Fb}});c=Hb(a,b,c,d);U(c.mode)?(c.Ta=T.gb.dir.node,c.Ua=T.gb.dir.stream,
c.Va={}):32768===(c.mode&61440)?(c.Ta=T.gb.file.node,c.Ua=T.gb.file.stream,c.$a=0,c.Va=null):40960===(c.mode&61440)?(c.Ta=T.gb.link.node,c.Ua=T.gb.link.stream):8192===(c.mode&61440)&&(c.Ta=T.gb.Nb.node,c.Ua=T.gb.Nb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Va[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},yc(a){return a.Va?a.Va.subarray?a.Va.subarray(0,a.$a):new Uint8Array(a.Va):new Uint8Array(0)},Ta:{bb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=
0;b.gid=0;b.rdev=a.rdev;U(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.$a:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},eb(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.$a!=b&&(0==b?(a.Va=null,a.$a=0):(c=a.Va,a.Va=new Uint8Array(b),c&&a.Va.set(c.subarray(0,Math.min(b,a.$a))),a.$a=b)))},lookup(){T.Cb||
(T.Cb=new R(44),T.Cb.stack="<generic error, no stack>");throw T.Cb;},xb(a,b,c,d){return T.createNode(a,b,c,d)},rename(a,b,c){try{var d=Ib(b,c)}catch(g){}if(d){if(U(a.mode))for(var f in d.Va)throw new R(55);Tb(d)}delete a.parent.Va[a.name];b.Va[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Va[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Ib(a,b),d;for(d in c.Va)throw new R(55);delete a.Va[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Va)]},
symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R(28);return a.link}},Ua:{read(a,b,c,d,f){var g=a.node.Va;if(f>=a.node.$a)return 0;a=Math.min(a.node.$a-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write(a,b,c,d,f,g){b.buffer===n.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Va||a.Va.subarray)){if(g)return a.Va=b.subarray(c,c+d),a.$a=d;if(0===a.$a&&
0===f)return a.Va=b.slice(c,c+d),a.$a=d;if(f+d<=a.$a)return a.Va.set(b.subarray(c,c+d),f),d}g=f+d;var p=a.Va?a.Va.length:0;p>=g||(g=Math.max(g,p*(1048576>p?2:1.125)>>>0),0!=p&&(g=Math.max(g,256)),p=a.Va,a.Va=new Uint8Array(g),0<a.$a&&a.Va.set(p.subarray(0,a.$a),0));if(a.Va.subarray&&b.subarray)a.Va.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Va[f+g]=b[c+g];a.$a=Math.max(a.$a,f+d);return d},fb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.$a);if(0>b)throw new R(28);
return b},yb(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new R(43);a=a.node.Va;if(f&2||!a||a.buffer!==n.buffer){f=!0;d=65536*Math.ceil(b/65536);var g=Vb(65536,d);g&&C.fill(0,g,g+d);d=g;if(!d)throw new R(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);n.set(a,d)}}else f=!1,d=a.byteOffset;return{oc:d,Ub:f}},zb(a,b,c,d){T.Ua.write(a,b,0,d,c,!1);return 0}}},ma=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Wb=null,Xb={},Yb=[],Zb=1,$b=null,ac=
!1,bc=!0,cc={},R=class{name="ErrnoError";constructor(a){this.Xa=a}},dc=class{wb={};node=null;get flags(){return this.wb.flags}set flags(a){this.wb.flags=a}get position(){return this.wb.position}set position(a){this.wb.position=a}},ec=class{Ta={};Ua={};qb=null;constructor(a,b,c,d){a||=this;this.parent=a;this.jb=a.jb;this.id=Zb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===
(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function V(a,b={}){if(!a)throw new R(44);b.Fb??(b.Fb=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(v=>!!v);for(var d=Wb,f="/",g=0;g<a.length;g++){var p=g===a.length-1;if(p&&b.parent)break;if("."!==a[g])if(".."===a[g])if(f=rb(f),d===d.parent){a=f+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{f=la(f+"/"+a[g]);try{d=Ib(d,a[g])}catch(v){if(44===v?.Xa&&p&&b.mc)return{path:f};throw v;}!d.qb||p&&!b.Fb||(d=d.qb.root);if(40960===(d.mode&61440)&&(!p||b.pb)){if(!d.Ta.readlink)throw new R(52);
d=d.Ta.readlink(d);"/"===d.charAt(0)||(d=rb(f)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:f,node:d}}throw new R(32);}function ka(a){for(var b;;){if(a===a.parent)return a=a.jb.Tb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function fc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%$b.length}
function Tb(a){var b=fc(a.parent.id,a.name);if($b[b]===a)$b[b]=a.rb;else for(b=$b[b];b;){if(b.rb===a){b.rb=a.rb;break}b=b.rb}}function Ib(a,b){var c=U(a.mode)?(c=gc(a,"x"))?c:a.Ta.lookup?0:2:54;if(c)throw new R(c);for(c=$b[fc(a.id,b)];c;c=c.rb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ta.lookup(a,b)}function Hb(a,b,c,d){a=new ec(a,b,c,d);b=fc(a.parent.id,a.name);a.rb=$b[b];return $b[b]=a}function U(a){return 16384===(a&61440)}
function hc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function gc(a,b){if(bc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ic(a,b){if(!U(a.mode))return 54;try{return Ib(a,b),20}catch(c){}return gc(a,"wx")}
function jc(a,b,c){try{var d=Ib(a,b)}catch(f){return f.Xa}if(a=gc(a,"wx"))return a;if(c){if(!U(d.mode))return 54;if(d===d.parent||"/"===ka(d))return 10}else if(U(d.mode))return 31;return 0}function kc(a){if(!a)throw new R(63);return a}function W(a){a=Yb[a];if(!a)throw new R(8);return a}function lc(a,b=-1){a=Object.assign(new dc,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!Yb[b])break a;throw new R(33);}a.fd=b;return Yb[b]=a}function mc(a,b=-1){a=lc(a,b);a.Ua?.wc?.(a);return a}
function nc(a,b,c){var d=a?.Ua.eb;a=d?a:b;d??=b.Ta.eb;kc(d);d(a,c)}var Fb={open(a){a.Ua=Xb[a.node.rdev].Ua;a.Ua.open?.(a)},fb(){throw new R(70);}};function Bb(a,b){Xb[a]={Ua:b}}function oc(a,b){var c="/"===b;if(c&&Wb)throw new R(10);if(!c&&b){var d=V(b,{Fb:!1});b=d.path;d=d.node;if(d.qb)throw new R(10);if(!U(d.mode))throw new R(54);}b={type:a,Cc:{},Tb:b,lc:[]};a=a.jb(b);a.jb=b;b.root=a;c?Wb=a:d&&(d.qb=b,d.jb&&d.jb.lc.push(b))}
function pc(a,b,c){var d=V(a,{parent:!0}).node;a=sb(a);if(!a)throw new R(28);if("."===a||".."===a)throw new R(20);var f=ic(d,a);if(f)throw new R(f);if(!d.Ta.xb)throw new R(63);return d.Ta.xb(d,a,b,c)}function na(a,b=438){return pc(a,b&4095|32768,0)}function X(a,b=511){return pc(a,b&1023|16384,0)}function qc(a,b,c){"undefined"==typeof c&&(c=b,b=438);pc(a,b|8192,c)}
function rc(a,b){if(!vb(a))throw new R(44);var c=V(b,{parent:!0}).node;if(!c)throw new R(44);b=sb(b);var d=ic(c,b);if(d)throw new R(d);if(!c.Ta.symlink)throw new R(63);c.Ta.symlink(c,b,a)}function sc(a){var b=V(a,{parent:!0}).node;a=sb(a);var c=Ib(b,a),d=jc(b,a,!0);if(d)throw new R(d);if(!b.Ta.rmdir)throw new R(63);if(c.qb)throw new R(10);b.Ta.rmdir(b,a);Tb(c)}
function Ba(a){var b=V(a,{parent:!0}).node;if(!b)throw new R(44);a=sb(a);var c=Ib(b,a),d=jc(b,a,!1);if(d)throw new R(d);if(!b.Ta.unlink)throw new R(63);if(c.qb)throw new R(10);b.Ta.unlink(b,a);Tb(c)}function tc(a,b){a=V(a,{pb:!b}).node;return kc(a.Ta.bb)(a)}function uc(a,b,c,d){nc(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),ac:d})}function qa(a,b){a="string"==typeof a?V(a,{pb:!0}).node:a;uc(null,a,b)}
function vc(a,b,c){if(U(b.mode))throw new R(31);if(32768!==(b.mode&61440))throw new R(28);var d=gc(b,"w");if(d)throw new R(d);nc(a,b,{size:c,timestamp:Date.now()})}
function ra(a,b,c=438){if(""===a)throw new R(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var f=a.endsWith("/");a=V(a,{pb:!(b&131072),mc:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new R(20);}else{if(f)throw new R(31);d=pc(a,c|511,0);g=!0}if(!d)throw new R(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!U(d.mode))throw new R(54);
if(!g&&(f=d?40960===(d.mode&61440)?32:U(d.mode)&&("r"!==hc(b)||b&576)?31:gc(d,hc(b)):44))throw new R(f);b&512&&!g&&(f=d,f="string"==typeof f?V(f,{pb:!0}).node:f,vc(null,f,0));b&=-131713;f=lc({node:d,path:ka(d),flags:b,seekable:!0,position:0,Ua:d.Ua,pc:[],error:!1});f.Ua.open&&f.Ua.open(f);g&&qa(d,c&511);!l.logReadFiles||b&1||a in cc||(cc[a]=1);return f}function ta(a){if(null===a.fd)throw new R(8);a.Gb&&(a.Gb=null);try{a.Ua.close&&a.Ua.close(a)}catch(b){throw b;}finally{Yb[a.fd]=null}a.fd=null}
function wc(a,b,c){if(null===a.fd)throw new R(8);if(!a.seekable||!a.Ua.fb)throw new R(70);if(0!=c&&1!=c&&2!=c)throw new R(28);a.position=a.Ua.fb(a,b,c);a.pc=[]}function xc(a,b,c,d,f){if(0>d||0>f)throw new R(28);if(null===a.fd)throw new R(8);if(1===(a.flags&2097155))throw new R(8);if(U(a.node.mode))throw new R(31);if(!a.Ua.read)throw new R(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new R(70);b=a.Ua.read(a,b,c,d,f);g||(a.position+=b);return b}
function sa(a,b,c,d,f){if(0>d||0>f)throw new R(28);if(null===a.fd)throw new R(8);if(0===(a.flags&2097155))throw new R(8);if(U(a.node.mode))throw new R(31);if(!a.Ua.write)throw new R(28);a.seekable&&a.flags&1024&&wc(a,0,2);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new R(70);b=a.Ua.write(a,b,c,d,f,void 0);g||(a.position+=b);return b}
function Aa(a){var b=b||0;var c="binary";"utf8"!==c&&"binary"!==c&&Za(`Invalid encoding type "${c}"`);b=ra(a,b);a=tc(a).size;var d=new Uint8Array(a);xc(b,d,0,a,0);"utf8"===c&&(d=wb(d));ta(b);return d}
function yc(a,b,c){a=la("/dev/"+a);var d=ma(!!b,!!c);yc.Sb??(yc.Sb=64);var f=yc.Sb++<<8|0;Bb(f,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,p,v,z){for(var x=0,B=0;B<z;B++){try{var L=b()}catch(hb){throw new R(29);}if(void 0===L&&0===x)throw new R(6);if(null===L||void 0===L)break;x++;p[v+B]=L}x&&(g.node.atime=Date.now());return x},write(g,p,v,z){for(var x=0;x<z;x++)try{c(p[v+x])}catch(B){throw new R(29);}z&&(g.node.mtime=g.node.ctime=Date.now());return x}});qc(a,d,f)}var Y={};
function zc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":W(a).path;if(0==b.length){if(!c)throw new R(44);return a}return a+"/"+b}
function Ac(a,b){I[a>>2]=b.dev;I[a+4>>2]=b.mode;I[a+8>>2]=b.nlink;I[a+12>>2]=b.uid;I[a+16>>2]=b.gid;I[a+20>>2]=b.rdev;O[a+24>>3]=BigInt(b.size);H[a+32>>2]=4096;H[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),f=b.ctime.getTime();O[a+40>>3]=BigInt(Math.floor(c/1E3));I[a+48>>2]=c%1E3*1E6;O[a+56>>3]=BigInt(Math.floor(d/1E3));I[a+64>>2]=d%1E3*1E6;O[a+72>>3]=BigInt(Math.floor(f/1E3));I[a+80>>2]=f%1E3*1E6;O[a+88>>3]=BigInt(b.ino);return 0}
var Mc=void 0,jd=()=>{var a=H[+Mc>>2];Mc+=4;return a},kd=0,ld=[0,31,60,91,121,152,182,213,244,274,305,335],md=[0,31,59,90,120,151,181,212,243,273,304,334],nd={},od=a=>{Ta=a;nb||0<kd||(l.onExit?.(a),Sa=!0);Da(a,new db(a))},pd=a=>{if(!Sa)try{a()}catch(b){b instanceof db||"unwind"==b||Da(1,b)}finally{if(!(nb||0<kd))try{Ta=a=Ta,od(a)}catch(b){b instanceof db||"unwind"==b||Da(1,b)}}},qd={},sd=()=>{if(!rd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??
"C").replace("-","_")+".UTF-8",_:Ca||"./this.program"},b;for(b in qd)void 0===qd[b]?delete a[b]:a[b]=qd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);rd=c}return rd},rd,td=(a,b,c,d)=>{var f={string:x=>{var B=0;if(null!==x&&void 0!==x&&0!==x){B=yb(x)+1;var L=ua(B);Q(x,C,L,B);B=L}return B},array:x=>{var B=ua(x.length);n.set(x,B);return B}};a=l["_"+a];var g=[],p=0;if(d)for(var v=0;v<d.length;v++){var z=f[c[v]];z?(0===p&&(p=xa()),g[v]=z(d[v])):g[v]=d[v]}c=a(...g);return c=function(x){0!==p&&za(p);return"string"===
b?E(x):"boolean"===b?!!x:x}(c)},ja=a=>{var b=yb(a)+1,c=ha(b);c&&Q(a,C,c,b);return c},ud,vd=[],D=a=>{ud.delete(wd.get(a));wd.set(a,null);vd.push(a)},xd=a=>{const b=a.length;return[b%128|128,b>>7,...a]},yd={i:127,p:127,j:126,f:125,d:124,e:111},zd=a=>xd(Array.from(a,b=>yd[b])),G=(a,b)=>{if(!ud){ud=new WeakMap;var c=wd.length;if(ud)for(var d=0;d<0+c;d++){var f=wd.get(d);f&&ud.set(f,d)}}if(c=ud.get(a)||0)return c;c=vd.length?vd.pop():wd.grow(1);try{wd.set(c,a)}catch(g){if(!(g instanceof TypeError))throw g;
b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...xd([1,96,...zd(b.slice(1)),...zd("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;wd.set(c,b)}ud.set(a,c);return c};$b=Array(4096);oc(T,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");Bb(259,{read:()=>0,write:(d,f,g,p)=>p,fb:()=>0});qc("/dev/null",259);Ab(1280,Db);Ab(1536,Eb);qc("/dev/tty",1280);qc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(ub(a),b=a.byteLength);return a[--b]};yc("random",c);yc("urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");oc({jb(){var b=Hb(a,"fd",16895,73);b.Ua={fb:T.Ua.fb};b.Ta={lookup(c,d){c=+d;var f=W(c);c={parent:null,jb:{Tb:"fake"},Ta:{readlink:()=>f.path},id:c+1};return c.parent=c},readdir(){return Array.from(Yb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();l.noExitRuntime&&(nb=l.noExitRuntime);l.print&&(Ka=l.print);l.printErr&&(Qa=l.printErr);l.wasmBinary&&(Ra=l.wasmBinary);l.thisProgram&&(Ca=l.thisProgram);
if(l.preInit)for("function"==typeof l.preInit&&(l.preInit=[l.preInit]);0<l.preInit.length;)l.preInit.shift()();l.stackSave=()=>xa();l.stackRestore=a=>za(a);l.stackAlloc=a=>ua(a);l.cwrap=(a,b,c,d)=>{var f=!c||c.every(g=>"number"===g||"boolean"===g);return"string"!==b&&f&&!d?l["_"+a]:(...g)=>td(a,b,c,g)};l.addFunction=G;l.removeFunction=D;l.UTF8ToString=E;l.stringToNewUTF8=ja;l.writeArrayToMemory=(a,b)=>{n.set(a,b)};
var ha,ia,Vb,Ad,za,ua,xa,Ya,wd,Bd={a:(a,b,c,d)=>Za(`Assertion failed: ${E(a)}, at: `+[b?E(b):"unknown filename",c,d?E(d):"unknown function"]),i:function(a,b){try{return a=E(a),qa(a,b),0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return-c.Xa}},L:function(a,b,c){try{b=E(b);b=zc(a,b);if(c&-8)return-28;var d=V(b,{pb:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&gc(d,a)?-2:0}catch(f){if("undefined"==typeof Y||"ErrnoError"!==f.name)throw f;return-f.Xa}},
j:function(a,b){try{var c=W(a);uc(c,c.node,b,!1);return 0}catch(d){if("undefined"==typeof Y||"ErrnoError"!==d.name)throw d;return-d.Xa}},h:function(a){try{var b=W(a);nc(b,b.node,{timestamp:Date.now(),ac:!1});return 0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return-c.Xa}},b:function(a,b,c){Mc=c;try{var d=W(a);switch(b){case 0:var f=jd();if(0>f)break;for(;Yb[f];)f++;return mc(d,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=jd(),d.flags|=f,0;case 12:return f=
jd(),Ua[f+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof Y||"ErrnoError"!==g.name)throw g;return-g.Xa}},g:function(a,b){try{var c=W(a),d=c.node,f=c.Ua.bb;a=f?c:d;f??=d.Ta.bb;kc(f);var g=f(a);return Ac(b,g)}catch(p){if("undefined"==typeof Y||"ErrnoError"!==p.name)throw p;return-p.Xa}},H:function(a,b){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-61;var c=W(a);if(0>b||0===(c.flags&2097155))throw new R(28);vc(c,c.node,b);return 0}catch(d){if("undefined"==
typeof Y||"ErrnoError"!==d.name)throw d;return-d.Xa}},G:function(a,b){try{if(0===b)return-28;var c=yb("/")+1;if(b<c)return-68;Q("/",C,a,b);return c}catch(d){if("undefined"==typeof Y||"ErrnoError"!==d.name)throw d;return-d.Xa}},K:function(a,b){try{return a=E(a),Ac(b,tc(a,!0))}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return-c.Xa}},C:function(a,b,c){try{return b=E(b),b=zc(a,b),X(b,c),0}catch(d){if("undefined"==typeof Y||"ErrnoError"!==d.name)throw d;return-d.Xa}},J:function(a,
b,c,d){try{b=E(b);var f=d&256;b=zc(a,b,d&4096);return Ac(c,f?tc(b,!0):tc(b))}catch(g){if("undefined"==typeof Y||"ErrnoError"!==g.name)throw g;return-g.Xa}},x:function(a,b,c,d){Mc=d;try{b=E(b);b=zc(a,b);var f=d?jd():0;return ra(b,c,f).fd}catch(g){if("undefined"==typeof Y||"ErrnoError"!==g.name)throw g;return-g.Xa}},v:function(a,b,c,d){try{b=E(b);b=zc(a,b);if(0>=d)return-28;var f=V(b).node;if(!f)throw new R(44);if(!f.Ta.readlink)throw new R(28);var g=f.Ta.readlink(f);var p=Math.min(d,yb(g)),v=n[c+p];
Q(g,C,c,d+1);n[c+p]=v;return p}catch(z){if("undefined"==typeof Y||"ErrnoError"!==z.name)throw z;return-z.Xa}},u:function(a){try{return a=E(a),sc(a),0}catch(b){if("undefined"==typeof Y||"ErrnoError"!==b.name)throw b;return-b.Xa}},f:function(a,b){try{return a=E(a),Ac(b,tc(a))}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return-c.Xa}},r:function(a,b,c){try{b=E(b);b=zc(a,b);if(c)if(512===c)sc(b);else return-28;else Ba(b);return 0}catch(d){if("undefined"==typeof Y||"ErrnoError"!==d.name)throw d;
return-d.Xa}},q:function(a,b,c){try{b=E(b);b=zc(a,b,!0);var d=Date.now(),f,g;if(c){var p=I[c>>2]+4294967296*H[c+4>>2],v=H[c+8>>2];1073741823==v?f=d:1073741822==v?f=null:f=1E3*p+v/1E6;c+=16;p=I[c>>2]+4294967296*H[c+4>>2];v=H[c+8>>2];1073741823==v?g=d:1073741822==v?g=null:g=1E3*p+v/1E6}else g=f=d;if(null!==(g??f)){a=f;var z=V(b,{pb:!0}).node;kc(z.Ta.eb)(z,{atime:a,mtime:g})}return 0}catch(x){if("undefined"==typeof Y||"ErrnoError"!==x.name)throw x;return-x.Xa}},m:()=>Za(""),l:()=>{nb=!1;kd=0},A:function(a,
b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);H[b>>2]=a.getSeconds();H[b+4>>2]=a.getMinutes();H[b+8>>2]=a.getHours();H[b+12>>2]=a.getDate();H[b+16>>2]=a.getMonth();H[b+20>>2]=a.getFullYear()-1900;H[b+24>>2]=a.getDay();var c=a.getFullYear();H[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?md:ld)[a.getMonth()]+a.getDate()-1|0;H[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();
H[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},y:function(a,b,c,d,f,g,p){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var v=W(d);if(0!==(b&2)&&0===(c&2)&&2!==(v.flags&2097155))throw new R(2);if(1===(v.flags&2097155))throw new R(2);if(!v.Ua.yb)throw new R(43);if(!a)throw new R(28);var z=v.Ua.yb(v,a,f,b,c);var x=z.oc;H[g>>2]=z.Ub;I[p>>2]=x;return 0}catch(B){if("undefined"==typeof Y||"ErrnoError"!==B.name)throw B;return-B.Xa}},z:function(a,b,c,d,f,g){g=-9007199254740992>g||
9007199254740992<g?NaN:Number(g);try{var p=W(f);if(c&2){c=g;if(32768!==(p.node.mode&61440))throw new R(43);if(!(d&2)){var v=C.slice(a,a+b);p.Ua.zb&&p.Ua.zb(p,v,c,b,d)}}}catch(z){if("undefined"==typeof Y||"ErrnoError"!==z.name)throw z;return-z.Xa}},n:(a,b)=>{nd[a]&&(clearTimeout(nd[a].id),delete nd[a]);if(!b)return 0;var c=setTimeout(()=>{delete nd[a];pd(()=>Ad(a,performance.now()))},b);nd[a]={id:c,Dc:b};return 0},B:(a,b,c,d)=>{var f=(new Date).getFullYear(),g=(new Date(f,0,1)).getTimezoneOffset();
f=(new Date(f,6,1)).getTimezoneOffset();I[a>>2]=60*Math.max(g,f);H[b>>2]=Number(g!=f);b=p=>{var v=Math.abs(p);return`UTC${0<=p?"-":"+"}${String(Math.floor(v/60)).padStart(2,"0")}${String(v%60).padStart(2,"0")}`};a=b(g);b=b(f);f<g?(Q(a,C,c,17),Q(b,C,d,17)):(Q(a,C,d,17),Q(b,C,c,17))},d:()=>Date.now(),s:()=>2147483648,c:()=>performance.now(),o:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
d)/65536))-Ya.buffer.byteLength+65535)/65536|0;try{Ya.grow(d);Xa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},E:(a,b)=>{var c=0,d=0,f;for(f of sd()){var g=b+c;I[a+d>>2]=g;c+=Q(f,C,g,Infinity)+1;d+=4}return 0},F:(a,b)=>{var c=sd();I[a>>2]=c.length;a=0;for(var d of c)a+=yb(d)+1;I[b>>2]=a;return 0},e:function(a){try{var b=W(a);ta(b);return 0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return c.Xa}},p:function(a,b){try{var c=W(a);n[b]=c.tty?2:U(c.mode)?3:40960===(c.mode&
61440)?7:4;Ua[b+2>>1]=0;O[b+8>>3]=BigInt(0);O[b+16>>3]=BigInt(0);return 0}catch(d){if("undefined"==typeof Y||"ErrnoError"!==d.name)throw d;return d.Xa}},w:function(a,b,c,d){try{a:{var f=W(a);a=b;for(var g,p=b=0;p<c;p++){var v=I[a>>2],z=I[a+4>>2];a+=8;var x=xc(f,n,v,z,g);if(0>x){var B=-1;break a}b+=x;if(x<z)break;"undefined"!=typeof g&&(g+=x)}B=b}I[d>>2]=B;return 0}catch(L){if("undefined"==typeof Y||"ErrnoError"!==L.name)throw L;return L.Xa}},D:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<
b?NaN:Number(b);try{if(isNaN(b))return 61;var f=W(a);wc(f,b,c);O[d>>3]=BigInt(f.position);f.Gb&&0===b&&0===c&&(f.Gb=null);return 0}catch(g){if("undefined"==typeof Y||"ErrnoError"!==g.name)throw g;return g.Xa}},I:function(a){try{var b=W(a);return b.Ua?.fsync?.(b)}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return c.Xa}},t:function(a,b,c,d){try{a:{var f=W(a);a=b;for(var g,p=b=0;p<c;p++){var v=I[a>>2],z=I[a+4>>2];a+=8;var x=sa(f,n,v,z,g);if(0>x){var B=-1;break a}b+=x;if(x<z)break;
"undefined"!=typeof g&&(g+=x)}B=b}I[d>>2]=B;return 0}catch(L){if("undefined"==typeof Y||"ErrnoError"!==L.name)throw L;return L.Xa}},k:od};
function Cd(){function a(){l.calledRun=!0;if(!Sa){if(!l.noFSInit&&!ac){var b,c;ac=!0;b??=l.stdin;c??=l.stdout;d??=l.stderr;b?yc("stdin",b):rc("/dev/tty","/dev/stdin");c?yc("stdout",null,c):rc("/dev/tty","/dev/stdout");d?yc("stderr",null,d):rc("/dev/tty1","/dev/stderr");ra("/dev/stdin",0);ra("/dev/stdout",1);ra("/dev/stderr",1)}Dd.N();bc=!1;l.onRuntimeInitialized?.();if(l.postRun)for("function"==typeof l.postRun&&(l.postRun=[l.postRun]);l.postRun.length;){var d=l.postRun.shift();fb.push(d)}eb(fb)}}
if(0<lb)mb=Cd;else{if(l.preRun)for("function"==typeof l.preRun&&(l.preRun=[l.preRun]);l.preRun.length;)kb();eb(gb);0<lb?mb=Cd:l.setStatus?(l.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>l.setStatus(""),1);a()},1)):a()}}var Dd;
(async function(){function a(c){c=Dd=c.exports;l._sqlite3_free=c.P;l._sqlite3_value_text=c.Q;l._sqlite3_prepare_v2=c.R;l._sqlite3_step=c.S;l._sqlite3_reset=c.T;l._sqlite3_exec=c.U;l._sqlite3_finalize=c.V;l._sqlite3_column_name=c.W;l._sqlite3_column_text=c.X;l._sqlite3_column_type=c.Y;l._sqlite3_errmsg=c.Z;l._sqlite3_clear_bindings=c._;l._sqlite3_value_blob=c.$;l._sqlite3_value_bytes=c.aa;l._sqlite3_value_double=c.ba;l._sqlite3_value_int=c.ca;l._sqlite3_value_type=c.da;l._sqlite3_result_blob=c.ea;
l._sqlite3_result_double=c.fa;l._sqlite3_result_error=c.ga;l._sqlite3_result_int=c.ha;l._sqlite3_result_int64=c.ia;l._sqlite3_result_null=c.ja;l._sqlite3_result_text=c.ka;l._sqlite3_aggregate_context=c.la;l._sqlite3_column_count=c.ma;l._sqlite3_data_count=c.na;l._sqlite3_column_blob=c.oa;l._sqlite3_column_bytes=c.pa;l._sqlite3_column_double=c.qa;l._sqlite3_bind_blob=c.ra;l._sqlite3_bind_double=c.sa;l._sqlite3_bind_int=c.ta;l._sqlite3_bind_text=c.ua;l._sqlite3_bind_parameter_index=c.va;l._sqlite3_sql=
c.wa;l._sqlite3_normalized_sql=c.xa;l._sqlite3_changes=c.ya;l._sqlite3_close_v2=c.za;l._sqlite3_progress_handler=c.Aa;l._sqlite3_interrupt=c.Ba;l._sqlite3_create_function_v2=c.Ca;l._sqlite3_update_hook=c.Da;l._sqlite3_open=c.Ea;l._sqlite3_get_autocommit=c.Fa;ha=l._malloc=c.Ga;ia=l._free=c.Ha;l._RegisterExtensionFunctions=c.Ia;l._sqljs_vfs_register=c.Ja;l._sqljs_open_paged=c.Ka;l._sqljs_vfs_register_rw=c.La;l._sqljs_open_paged_rw=c.Ma;l._sqlite_explorer_register_query_plan=c.Na;Vb=c.Oa;Ad=c.Pa;za=
c.Qa;ua=c.Ra;xa=c.Sa;Ya=c.M;wd=c.O;Xa();lb--;l.monitorRunDependencies?.(lb);0==lb&&mb&&(c=mb,mb=null,c());return Dd}lb++;l.monitorRunDependencies?.(lb);var b={a:Bd};if(l.instantiateWasm)return new Promise(c=>{l.instantiateWasm(b,(d,f)=>{c(a(d,f))})});$a??=l.locateFile?l.locateFile("sql-wasm.wasm",Fa):Fa+"sql-wasm.wasm";return a((await cb(b)).instance)})();Cd();


        // The shell-pre.js and emcc-generated code goes above
        return Module;
    }); // The end of the promise being returned

  return initSqlJsPromise;
} // The end of our initSqlJs function

// This bit below is copied almost exactly from what you get when you use the MODULARIZE=1 flag with emcc
// However, we don't want to use the emcc modularization. See shell-pre.js
if (typeof exports === 'object' && typeof module === 'object'){
    module.exports = initSqlJs;
    // This will allow the module to be used in ES6 or CommonJS
    module.exports.default = initSqlJs;
}
else if (typeof define === 'function' && define['amd']) {
    define([], function() { return initSqlJs; });
}
else if (typeof exports === 'object'){
    exports["Module"] = initSqlJs;
}
